[placeholders]
commandline_args = { prompt = "Do you wish to parse command line arguments (clap)?", default = true, type = "bool" }
xdg = { prompt = "Do you wish to access linux user directories (xdg)?", default = true, type = "bool" }
request = { prompt = "Do you wish to request something from the internet (reqwest)?", default = false, type = "bool" }
locale = { prompt = "Do you wish to locale your project (rust-i18n)?", default = true, type = "bool" }
serde = { prompt = "Do you wish to serialize and deserialize (serde)?", default = true, type = "bool" }
async = { prompt = "Do you wish to use async (TOKIOOOO!!!!)?", default = false, type = "bool" }
license = { prompt = "Customize license default (only GPL-v3)?", default = false, type = "bool" }

[template]
ignore = [
  "target",
  "Cargo.lock"
]

[hooks]
pre = ["pre-script.rhai"]
post = ["post-script.rhai"]
